# Broadcast Prefix#
# Prefix: '&3Broadcast &a>&e'#
# Version of the config!#
# Do not touch this option!#
# Version: 5#
# Settings:#
#   Delay-Time: 2400 # 20 ticks = 1 second! 1200 = 1 minute!#
#   Sound-on-broadcast: #
#      Enabled: true #Enables Sound-On-Broadcast!#
#      Pitch: 5#Pitch of the sound#
#      Sound: BLOCK_NOTE_HARP #Sound of the broadcast! See all sound here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html#

Prefix: '&3Broadcast &a>&e'
Version: 5
Settings:
   Delay-Time: 2400
   Sound-on-broadcast:
      Enabled: true
      Sound: BLOCK_NOTE_HARP
      Pitch: 5